FROM fedora:41


RUN yum -y install httpd php php-cli php-common mod_ssl openssl


COPY ssl.conf /etc/httpd/conf.d/default.conf

COPY docker.crt /docker.crt

COPY docker.key /docker.key

### Fedora requirement:

COPY docker.crt /etc/pki/tls/certs/localhost.crt
COPY docker.key /etc/pki/tls/private/localhost.key

CMD mkdir /run/php-fpm && php-fpm && httpd -D FOREGROUND
